import prisma from "../src/lib/db";

function slug(name: string, suffix: string) {
  return (
    name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") +
    "-" +
    suffix
  );
}

const venues = [
  // ── Wedding Venues ──────────────────────────────────────────────────
  {
    name: "Grand Lakeside Mansion",
    slug: slug("Grand Lakeside Mansion", "wv-001"),
    category: "wedding",
    type: "Mansion",
    location: "Stockholm, SE",
    city: "Stockholm",
    rating: 4.9,
    reviewCount: 128,
    price: 45000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80",
    badge: "Popular",
    badgeColor: "purple",
    tags: ["Up to 300", "Indoor", "Outdoor", "Catering"],
    isFeatured: true,
  },
  {
    name: "Rose Garden Estate",
    slug: slug("Rose Garden Estate", "wv-002"),
    category: "wedding",
    type: "Garden",
    location: "Gothenburg, SE",
    city: "Gothenburg",
    rating: 4.8,
    reviewCount: 96,
    price: 32000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80",
    badge: "Featured",
    badgeColor: "orange",
    tags: ["Up to 200", "Outdoor", "Garden", "Romantic"],
    isFeatured: true,
  },
  {
    name: "Vineyard Terrace Winery",
    slug: slug("Vineyard Terrace Winery", "wv-003"),
    category: "wedding",
    type: "Winery",
    location: "Malmö, SE",
    city: "Malmö",
    rating: 4.7,
    reviewCount: 74,
    price: 28000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80",
    badge: null,
    badgeColor: null,
    tags: ["Up to 150", "Indoor", "Wine Tasting", "Rustic"],
    isFeatured: false,
  },
  {
    name: "Crystal Ballroom",
    slug: slug("Crystal Ballroom", "wv-004"),
    category: "wedding",
    type: "Banquet Hall",
    location: "Uppsala, SE",
    city: "Uppsala",
    rating: 4.8,
    reviewCount: 112,
    price: 38000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1532117182044-031e7cd916ee?w=800&q=80",
    badge: "Popular",
    badgeColor: "purple",
    tags: ["Up to 400", "Indoor", "Dance Floor", "AV Included"],
    isFeatured: true,
  },
  {
    name: "Azure Beach Club",
    slug: slug("Azure Beach Club", "wv-005"),
    category: "wedding",
    type: "Beach Venue",
    location: "Visby, SE",
    city: "Visby",
    rating: 4.9,
    reviewCount: 88,
    price: 55000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80",
    badge: "Featured",
    badgeColor: "orange",
    tags: ["Up to 250", "Outdoor", "Beachfront", "Sunset Views"],
    isFeatured: true,
  },
  {
    name: "Whitewood Manor",
    slug: slug("Whitewood Manor", "wv-006"),
    category: "wedding",
    type: "Mansion",
    location: "Örebro, SE",
    city: "Örebro",
    rating: 4.6,
    reviewCount: 52,
    price: 42000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1478860409698-8707f313ee8b?w=800&q=80",
    badge: null,
    badgeColor: null,
    tags: ["Up to 180", "Indoor", "Historic", "Gardens"],
    isFeatured: false,
  },

  // ── Party & Event Venues ────────────────────────────────────────────
  {
    name: "Skyline Event Hall",
    slug: slug("Skyline Event Hall", "pv-001"),
    category: "party",
    type: "Party Hall",
    location: "Stockholm, SE",
    city: "Stockholm",
    rating: 4.7,
    reviewCount: 143,
    price: 18000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
    badge: "Popular",
    badgeColor: "purple",
    tags: ["Up to 500", "Indoor", "Sound System", "Bar"],
    isFeatured: true,
  },
  {
    name: "Nordic Conference Center",
    slug: slug("Nordic Conference Center", "pv-002"),
    category: "party",
    type: "Conference Center",
    location: "Gothenburg, SE",
    city: "Gothenburg",
    rating: 4.5,
    reviewCount: 67,
    price: 22000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    badge: null,
    badgeColor: null,
    tags: ["Up to 600", "Indoor", "AV Included", "Breakout Rooms"],
    isFeatured: false,
  },
  {
    name: "Grand Hotel Ballroom",
    slug: slug("Grand Hotel Ballroom", "pv-003"),
    category: "party",
    type: "Hotel",
    location: "Malmö, SE",
    city: "Malmö",
    rating: 4.8,
    reviewCount: 98,
    price: 35000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    badge: "Featured",
    badgeColor: "orange",
    tags: ["Up to 350", "Indoor", "Catering", "Accommodation"],
    isFeatured: true,
  },
  {
    name: "The Old Parliament House",
    slug: slug("The Old Parliament House", "pv-004"),
    category: "party",
    type: "Historic Venue",
    location: "Stockholm, SE",
    city: "Stockholm",
    rating: 4.9,
    reviewCount: 45,
    price: 60000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=800&q=80",
    badge: "Popular",
    badgeColor: "purple",
    tags: ["Up to 200", "Indoor", "Historic", "Exclusive"],
    isFeatured: true,
  },
  {
    name: "Archipelago Yacht Charter",
    slug: slug("Archipelago Yacht Charter", "pv-005"),
    category: "party",
    type: "Yacht & Boat",
    location: "Stockholm Archipelago, SE",
    city: "Stockholm",
    rating: 4.8,
    reviewCount: 61,
    price: 48000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    badge: null,
    badgeColor: null,
    tags: ["Up to 80", "On Water", "Catering", "Scenic"],
    isFeatured: false,
  },
  {
    name: "Forest Clearing Outdoor",
    slug: slug("Forest Clearing Outdoor", "pv-006"),
    category: "party",
    type: "Outdoor Venue",
    location: "Västerås, SE",
    city: "Västerås",
    rating: 4.6,
    reviewCount: 39,
    price: 12000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=800&q=80",
    badge: null,
    badgeColor: null,
    tags: ["Up to 1000", "Outdoor", "Nature", "Flexible"],
    isFeatured: false,
  },

  // ── Specialty Venues ────────────────────────────────────────────────
  {
    name: "Uppsala Cathedral Hall",
    slug: slug("Uppsala Cathedral Hall", "sv-001"),
    category: "specialty",
    type: "Religious Venue",
    location: "Uppsala, SE",
    city: "Uppsala",
    rating: 4.9,
    reviewCount: 77,
    price: 25000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80",
    badge: "Popular",
    badgeColor: "purple",
    tags: ["Up to 300", "Indoor", "Sacred", "Historic"],
    isFeatured: true,
  },
  {
    name: "Château de Lumière",
    slug: slug("Chateau de Lumiere", "sv-002"),
    category: "specialty",
    type: "Luxury Estate",
    location: "Sigtuna, SE",
    city: "Sigtuna",
    rating: 5.0,
    reviewCount: 34,
    price: 85000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    badge: "Featured",
    badgeColor: "orange",
    tags: ["Up to 120", "Indoor", "Outdoor", "Exclusive", "Luxury"],
    isFeatured: true,
  },
  {
    name: "Santorini Destination Venue",
    slug: slug("Santorini Destination Venue", "sv-003"),
    category: "specialty",
    type: "Destination Venue",
    location: "Santorini, GR",
    city: "Santorini",
    rating: 4.9,
    reviewCount: 156,
    price: 120000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    badge: "Popular",
    badgeColor: "purple",
    tags: ["Up to 100", "Outdoor", "International", "Scenic"],
    isFeatured: true,
  },
  {
    name: "Modern Art Gallery Space",
    slug: slug("Modern Art Gallery Space", "sv-004"),
    category: "specialty",
    type: "Unique Space",
    location: "Stockholm, SE",
    city: "Stockholm",
    rating: 4.7,
    reviewCount: 58,
    price: 30000,
    priceUnit: "/day",
    image: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&q=80",
    badge: null,
    badgeColor: null,
    tags: ["Up to 200", "Indoor", "Art", "Contemporary"],
    isFeatured: false,
  },
];

async function main() {
  console.log("Seeding venues...");

  for (const venue of venues) {
    await prisma.venue.upsert({
      where: { slug: venue.slug },
      update: {
        name: venue.name,
        category: venue.category,
        type: venue.type,
        location: venue.location ?? null,
        city: venue.city ?? null,
        rating: venue.rating,
        reviewCount: venue.reviewCount,
        price: venue.price ?? null,
        priceUnit: venue.priceUnit,
        image: venue.image ?? null,
        badge: venue.badge ?? null,
        badgeColor: venue.badgeColor ?? null,
        tags: venue.tags,
        isFeatured: venue.isFeatured,
      },
      create: {
        ...venue,
        location: venue.location ?? null,
        city: venue.city ?? null,
        price: venue.price ?? null,
        badge: venue.badge ?? null,
        badgeColor: venue.badgeColor ?? null,
        description: null,
        href: null,
        isActive: true,
        sortOrder: 0,
      },
    });
    console.log(`  ✓ ${venue.name}`);
  }

  console.log(`\nDone. ${venues.length} venues seeded.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
